name: CI Spring Boot

on:
  push:
    branches:
      - main  # Ejecutar el workflow cuando hagas push a la rama main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout del código fuente
      - name: Checkout source code
        uses: actions/checkout@v2

      # 2️⃣ Configurar Java 21
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: 21
          distribution: temurin

      # 3️⃣ Compilar y ejecutar pruebas
      - name: Build and test with Maven
        run: |
          mvn clean package
          mvn test
